### ISSUE TITLE
Bash driver is not a detected language

### ISSUE THREAD

**Issue by smola** [bblfsh/bash-driver#39]
We use enry for language detection both on bblfshd side as well as on our applications. Enry, as well as github/linguist, do not detect Bash itself, but just Shell (this includes the whole family of POSIX-like shell languages).

This generates the following problem:
- A bash file will never be routed to bash-driver if using automatic language detection at bblfshd side.
- If we use enry in our applications, we'll never use bash-driver out of the box either.

**Comment by juanjux** [comment]
As @mcuadros said, we could also modify enry. Alternatively, we could support more than one language name per driver in the manifest.

**Comment by bzz** [comment]
>  support more than one language name per driver in the manifest
I like this idea as it simplifies things for clinets as they can just call bblfsh with output of enry

**Comment by bzz** [comment]
Small summary of the context for this issue below.

## Use case
 - client asks bblfshd for list of the supported languages
 - client uses enry to detect language and if it's supported
 - client asks bblfshd to parse \w a given language

## Problem
 - "Language" field from the driver manifest can be different from language identifier that Enry uses.
   Example: bash (manifest) VS shell (enry)

## Alternatives
 1. 🙅‍♂️ rename driver to `shell-driver`. Discarded, see https://github.com/bblfsh/bblfshd/issues/162#issuecomment-411034652
 2. change `Language` field to support multiple drivers (either as array, or as a string \w separator)
    - "language" field is used in many places for different purposes
    - changes would be invasive and include code for new driver generation, etc, etc
 3. add new field to manifest "enry_languages"
    - use it to map incoming "language" from parse requests, before [DriverPool](https://github.com/bblfsh/bblfshd/blob/6f082d7a918a918725f777a69a2c35eb33cb877e/daemon/service.go#L78) selection
    - depending on whether we want to impose changes on [clients](https://github.com/src-d/gitbase/blob/42bbecace46b6bfe2b7eec73312679a4b1b54132/session.go#L128) or not:
       * either just add new field to v1 `protocol1.DriverManifest` and expect clients to update client version and read it instead
       * or  reply to [`protocol1.SupportedLanguages`]( https://github.com/bblfsh/sdk/blob/910019c320386fa99a2e283d80c5c1769717d545/driver/server/grpc.go#L63) with additional "fake" `DriverManifest`, one per each item of `"enry_languages"` arrays.


It may be a good time to implement any of this directly in v2, when we decide to port `SupportedLanguagesRequest` from protocol v1 to v2.

**Comment by juanjux** [comment]
My proposal (make the languages field a list or a string with a separator) doesn't imply generating multiple drivers, just multiple names for the same drivers.

**Comment by bzz** [comment]
> My proposal (make the languages field a list or a string with a separator) doesn't imply generating multiple drivers, just multiple names for the same drivers.

I'm not familiar with the codebase very much, but a quick glance showed that in this case, on top of the mandatory changes listed in 3, we would also need to
 - update the protocol definition (if changing a field type)
 - introduce new special logic in driver generation, as "language" field is used all over templates 

Would not that be the case?

**Comment by juanjux** [comment]
Yes, changes are going to be needed in any case. We could also keep the same language field and all a "language_aliases" field (instead of "enry_languages" so we're not tying the drivers to enry in any way).

**Comment by smola** [comment]
I would rather use something like `language_aliases` to avoid tying the protocol to enry itself. If we really wanted this to reference enry, I would reference linguist instead (`linguist_languages`), since that is our ground truth for language names.

**Comment by bzz** [comment]
@juanjux @smola `language_aliases` thank you guys, makes perfect sense 👍 Updated the msg above.

Having a separate field have benefits that at least we do not need to touch any templates/driver generation part. So far, the only changes that I found to be needed in this case seem to be well localized and are listed in 3. (And we even seem to have an option of not changing a protocol1 at all! I vote for that.)

**Comment by juanjux** [comment]
I'm fine with the new field then, too.
