### ISSUE TITLE
Bash driver doesn't generate tests from source files

### ISSUE THREAD

**Issue by tsolakoua** [bblfsh/bash-driver#45]
Since last night I am trying to generate tests for the bash-driver unsuccessfully. 

First, my source files where ```.sh```, the ```bblfsh-sdk test``` was running without errors, but no output generated. 

I changed my files to ```.bash``` and I see the followings.
``` 
TestBashDriver/semantic/bench_ethopian_multiplication (2.01s)
        	require.go:794: 
        			Error Trace:	fixtures.go:241
        			Error:      	Received unexpected error:
        			            	driver failure: read |0: i/o timeout
        			            	
        			            	github.com/bblfsh/bash-driver/vendor/gopkg.in/bblfsh/sdk.v2/driver/native.(*Driver).Parse
        			            		/go/src/github.com/bblfsh/bash-driver/vendor/gopkg.in/bblfsh/sdk.v2/driver/native/native.go:213
        			            	github.com/bblfsh/bash-driver/vendor/gopkg.in/bblfsh/sdk.v2/driver/fixtures.(*Suite).testFixturesUAST.func1
        			            		/go/src/github.com/bblfsh/bash-driver/vendor/gopkg.in/bblfsh/sdk.v2/driver/fixtures/fixtures.go:232
        			            	testing.tRunner
        			            		/usr/local/go/src/testing/testing.go:777
        			            	runtime.goexit
        			            		/usr/local/go/src/runtime/asm_amd64.s:2361
        			Test:       	TestBashDriver/semantic/bench_ethopian_multiplication
FAIL
```

If you think there might be something wrong with my files, I can make a PR with them. 
From RosettaCode, the source code of the files I used is in```Unix shell```.

**Comment by juanjux** [comment]
It worked for me with the files you passed on Slack. Looks like a timeout so your computer is probably slower than mine (Linux > macOs :laughing: ), still be should probably increase that timeout.

**Comment by juanjux** [comment]
It's the `bash_accumulator_factory.bash` test that's causing the problem. It fails (both on fixtures generation or trying to parse it with a client) with a `context deadline exceeded` errors; all the other `bench_` tests work perfectly but show errors after this one fails (removing it make all the fixtures work). 

I'm investigating why this one fails.

**Comment by tsolakoua** [comment]
I took the script from [here](https://rosettacode.org/wiki/Accumulator_factory#UNIX_Shell), not sure if it matters that it says it works with ```pdksh```.

**Comment by dennwc** [comment]
If tests fail after a single broken file, I suspect that the native driver prints a stack trace to stdout, breaking the protocol. If it's correct, then we may want to change it to print to stderr (if possible).

**Comment by juanjux** [comment]
In this case the native driver just stops without any kind of output or error:

```
$ sh native.sh 
{"content": "#!/bin/sh\naccumulator() {\n\t# Define a global function named $1\n\t# with a global variable named ${1}_sum.\n\teval \"${1}_sum=\\$2\"\n\teval \"$1() {\n\t\t${1}_sum=\\$(echo \\\"(\\$${1}_sum) + (\\$2)\\\" | bc)\n\t\teval \\\"\\$1=\\\\\\$${1}_sum\\\"  # Provide the current sum.\n\t}\"\n}\n \naccumulator x 1\nx r 5\naccumulator y 3\nx r 2.3\necho $r\ny r -3000\necho $r\n", "filepath": "/home/juanjux/borrame/bench_accumulator_factory.bash"}
$
```

Currently investigating why.

**Comment by juanjux** [comment]
Update: the error handling in the driver was broken in a very specific case resulting in silent exits. This will be fixed on the next PR so the driver shouldn't hang anymore (plus writing the full stacktrace to std error to help debugging in the future). Now I need to fix the `NullPointerException` that was the real error that was happening.

**Comment by juanjux** [comment]
Update: it's, unfortunatelly, an error in the intellij lib we're using, tried with an updated version of the dependencies and it still happens, I'll open an issue with them, but since the issue was about the driver timing out because it was unresponsive and that should be fixed the next PR should fix this.
